#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
yabai -m config                                 \
    external_bar                 all:25:0       \
    menubar_opacity              0.9            \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.2            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.2            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0x88d4be98     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Calculator$" manage=off 
yabai -m rule --add app="^Steam$" manage=off

yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"

echo "yabai configuration loaded.."
